# Generated by Django 3.2.9 on 2021-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptAnimal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
